import Head from 'next/head';
import Header from '../header/Header';
import Footer from '../footer/Footer';

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Football Stats</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/1.9.2/tailwind.min.css"></link>
      </Head>

      <Header />
      <main>{children}</main>
      <Footer />
    </>
  );
}

export default Layout;
